apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-html
  labels:
    app: app-html
spec:
  replicas: 5
  selector:
    matchLabels:
      app: app-html
  template:
    metadata:
      labels:
        app: app-html
    spec:
      containers:
      - name: app-html
        image: jdoteduardo11/app-html:1.1
        ports:
        - containerPort: 80